import Header from "./components/Header";
import InputForm from "./components/InputForm/InputForm";
import ResultsDashboard from "./components/Results/ResultsDashboard";
import useEmissionCalculator from "./hooks/useEmissionCalculator";
import { generateRecommendations } from "./utils/calculations";

const CarbonFootprintCalculator: React.FC = () => {
  const {
    formData,
    results,
    handleInputChange,
    calculateEmissions,
    resetCalculator,
    getTotalEmissions,
  } = useEmissionCalculator();

  const downloadReport = () => {
    if (!results) return;

    const total = getTotalEmissions();
    const recommendations = generateRecommendations(results);
    const reportContent = `
CARBON FOOTPRINT REPORT
========================
Generated: ${new Date().toLocaleDateString()}

TOTAL EMISSIONS: ${total.toFixed(2)} kg CO₂

BREAKDOWN BY CATEGORY:
${results
  .map((item) => `${item.category}: ${item.emissions.toFixed(2)} kg CO₂`)
  .join("\n")}

PERSONALIZED RECOMMENDATIONS:
${recommendations.map((rec, i) => `${i + 1}. ${rec}`).join("\n")}

---
Generated by Carbon Footprint Calculator
Built with React, TypeScript, and TailwindCSS
    `;

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `carbon-footprint-report-${
      new Date().toISOString().split("T")[0]
    }.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-blue-50 to-purple-50 p-4 md:p-8 relative overflow-hidden">
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-20 left-10 w-72 h-72 bg-green-300 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob"></div>
        <div className="absolute top-40 right-10 w-72 h-72 bg-blue-300 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-2000"></div>
        <div className="absolute -bottom-20 left-1/2 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-4000"></div>
      </div>

      <div className="max-w-7xl mx-auto relative z-10">
        <Header />

        {!results ? (
          <InputForm
            formData={formData}
            onChange={handleInputChange}
            onCalculate={calculateEmissions}
          />
        ) : (
          <ResultsDashboard
            results={results}
            totalEmissions={getTotalEmissions()}
            onDownload={downloadReport}
            onReset={resetCalculator}
          />
        )}

        <div className="mt-16 text-center text-gray-600 text-sm">
          <p className="font-semibold mb-2">
            Built with React, TypeScript, and TailwindCSS
          </p>
          <p className="mt-2">
            Emission factors based on German averages and international
            standards
          </p>
        </div>
      </div>
    </div>
  );
};

export default CarbonFootprintCalculator;
